on: push

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: ./build.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: Build artifacts
          path: Build/Publish/*.nupkg
